version: '3'

services:
  mysql:
    image: mysql
    restart: always
    ports:
      - '3307:3306'
    environment:
      TZ: Asia/Shanghai
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_DATABASE: nest_server
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_general_ci',
      ]
